import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'en' | 'hi' | 'mr' | 'ta' | 'bn' | 'ml';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    appName: "MedMitra Assistant",
    login: "Login",
    signup: "Sign Up",
    email: "Email",
    password: "Password",
    confirmPassword: "Confirm Password",
    fullName: "Full Name",
    phone: "Phone Number",
    age: "Age",
    gender: "Gender",
    male: "Male",
    female: "Female",
    other: "Other",
    location: "Location",
    dashboard: "Dashboard",
    logout: "Logout",
    healthTips: "Health Tips",
    vaccination: "Vaccination Schedule",
    outbreakAlerts: "Outbreak Alerts",
    hospitals: "Find Hospitals",
    notifications: "Notifications",
    chatbot: "Chat Assistant",
    emergency: "Emergency Help",
    familyMembers: "Family Members",
    symptomChecker: "Symptom Checker",
    enterSymptoms: "Enter your symptoms...",
    send: "Send",
    viewAll: "View All",
    dueDate: "Due Date",
    status: "Status",
    pending: "Pending",
    completed: "Completed",
    severity: "Severity",
    high: "High",
    medium: "Medium",
    low: "Low",
    address: "Address",
    contact: "Contact",
    availability: "Availability",
    available: "Available",
    busy: "Busy",
    getDirections: "Get Directions",
    typeMessage: "Type your message...",
    startChat: "Start chatting with MedMitra...",
    voiceInput: "Voice Input",
    alreadyHaveAccount: "Already have an account?",
    dontHaveAccount: "Don't have an account?",
  },
  hi: {
    appName: "आशा स्वास्थ्य सहायक",
    login: "लॉग इन करें",
    signup: "साइन अप करें",
    email: "ईमेल",
    password: "पासवर्ड",
    confirmPassword: "पासवर्ड की पुष्टि करें",
    fullName: "पूरा नाम",
    phone: "फ़ोन नंबर",
    age: "उम्र",
    gender: "लिंग",
    male: "पुरुष",
    female: "महिला",
    other: "अन्य",
    location: "स्थान",
    dashboard: "डैशबोर्ड",
    logout: "लॉग आउट",
    healthTips: "स्वास्थ्य सुझाव",
    vaccination: "टीकाकरण कार्यक्रम",
    outbreakAlerts: "प्रकोप अलर्ट",
    hospitals: "अस्पताल खोजें",
    notifications: "सूचनाएं",
    chatbot: "चैट सहायक",
    emergency: "आपातकालीन सहायता",
    familyMembers: "परिवार के सदस्य",
    symptomChecker: "लक्षण जांचकर्ता",
    enterSymptoms: "अपने लक्षण दर्ज करें...",
    send: "भेजें",
    viewAll: "सभी देखें",
    dueDate: "नियत तारीख",
    status: "स्थिति",
    pending: "लंबित",
    completed: "पूर्ण",
    severity: "गंभीरता",
    high: "उच्च",
    medium: "मध्यम",
    low: "कम",
    address: "पता",
    contact: "संपर्क",
    availability: "उपलब्धता",
    available: "उपलब्ध",
    busy: "व्यस्त",
    getDirections: "दिशा निर्देश प्राप्त करें",
    typeMessage: "अपना संदेश लिखें...",
    startChat: "आशा के साथ चैट शुरू करें...",
    voiceInput: "आवाज इनपुट",
    alreadyHaveAccount: "पहले से एक खाता है?",
    dontHaveAccount: "खाता नहीं है?",
  },
  mr: {
    appName: "आशा आरोग्य सहाय्यक",
    login: "लॉगिन करा",
    signup: "साइन अप करा",
    email: "ईमेल",
    password: "पासवर्ड",
    confirmPassword: "पासवर्डची पुष्टी करा",
    fullName: "पूर्ण नाव",
    phone: "फोन नंबर",
    age: "वय",
    gender: "लिंग",
    male: "पुरुष",
    female: "महिला",
    other: "इतर",
    location: "स्थान",
    dashboard: "डॅशबोर्ड",
    logout: "लॉग आउट",
    healthTips: "आरोग्य सल्ले",
    vaccination: "लसीकरण वेळापत्रक",
    outbreakAlerts: "उद्रेक सूचना",
    hospitals: "रुग्णालये शोधा",
    notifications: "सूचना",
    chatbot: "चॅट सहाय्यक",
    emergency: "आपत्कालीन मदत",
    familyMembers: "कुटुंब सदस्य",
    symptomChecker: "लक्षण तपासणी",
    enterSymptoms: "तुमची लक्षणे प्रविष्ट करा...",
    send: "पाठवा",
    viewAll: "सर्व पहा",
    dueDate: "देय तारीख",
    status: "स्थिती",
    pending: "प्रलंबित",
    completed: "पूर्ण",
    severity: "तीव्रता",
    high: "उच्च",
    medium: "मध्यम",
    low: "कमी",
    address: "पत्ता",
    contact: "संपर्क",
    availability: "उपलब्धता",
    available: "उपलब्ध",
    busy: "व्यस्त",
    getDirections: "दिशानिर्देश मिळवा",
    typeMessage: "तुमचा संदेश टाइप करा...",
    startChat: "आशासोबत चॅट सुरू करा...",
    voiceInput: "आवाज इनपुट",
    alreadyHaveAccount: "आधीपासून खाते आहे?",
    dontHaveAccount: "खाते नाही?",
  },
  ta: {
    appName: "ஆஷா சுகாதார உதவியாளர்",
    login: "உள்நுழைய",
    signup: "பதிவு செய்யவும்",
    email: "மின்னஞ்சல்",
    password: "கடவுச்சொல்",
    confirmPassword: "கடவுச்சொல்லை உறுதிப்படுத்தவும்",
    fullName: "முழு பெயர்",
    phone: "தொலைபேசி எண்",
    age: "வயது",
    gender: "பாலினம்",
    male: "ஆண்",
    female: "பெண்",
    other: "மற்றவை",
    location: "இடம்",
    dashboard: "டாஷ்போர்டு",
    logout: "வெளியேறு",
    healthTips: "சுகாதார உதவிக்குறிப்புகள்",
    vaccination: "தடுப்பூசி அட்டவணை",
    outbreakAlerts: "வெடிப்பு எச்சரிக்கைகள்",
    hospitals: "மருத்துவமனைகளைக் கண்டறியவும்",
    notifications: "அறிவிப்புகள்",
    chatbot: "அரட்டை உதவியாளர்",
    emergency: "அவசர உதவி",
    familyMembers: "குடும்ப உறுப்பினர்கள்",
    symptomChecker: "அறிகுறி சரிபார்ப்பு",
    enterSymptoms: "உங்கள் அறிகுறிகளை உள்ளிடவும்...",
    send: "அனுப்பு",
    viewAll: "அனைத்தையும் பார்",
    dueDate: "நிலுவை தேதி",
    status: "நிலை",
    pending: "நிலுவையில்",
    completed: "முடிந்தது",
    severity: "தீவிரம்",
    high: "உயர்",
    medium: "நடுத்தர",
    low: "குறைந்த",
    address: "முகவரி",
    contact: "தொடர்பு",
    availability: "கிடைக்கும் தன்மை",
    available: "கிடைக்கிறது",
    busy: "பிஸி",
    getDirections: "திசைகளைப் பெறுங்கள்",
    typeMessage: "உங்கள் செய்தியைத் தட்டச்சு செய்யவும்...",
    startChat: "ஆஷாவுடன் அரட்டை தொடங்கவும்...",
    voiceInput: "குரல் உள்ளீடு",
    alreadyHaveAccount: "ஏற்கனவே கணக்கு உள்ளதா?",
    dontHaveAccount: "கணக்கு இல்லையா?",
  },
  bn: {
    appName: "আশা স্বাস্থ্য সহায়ক",
    login: "লগইন করুন",
    signup: "সাইন আপ করুন",
    email: "ইমেল",
    password: "পাসওয়ার্ড",
    confirmPassword: "পাসওয়ার্ড নিশ্চিত করুন",
    fullName: "পুরো নাম",
    phone: "ফোন নম্বর",
    age: "বয়স",
    gender: "লিঙ্গ",
    male: "পুরুষ",
    female: "মহিলা",
    other: "অন্যান্য",
    location: "অবস্থান",
    dashboard: "ড্যাশবোর্ড",
    logout: "লগআউট",
    healthTips: "স্বাস্থ্য পরামর্শ",
    vaccination: "টিকা সময়সূচী",
    outbreakAlerts: "প্রাদুর্ভাব সতর্কতা",
    hospitals: "হাসপাতাল খুঁজুন",
    notifications: "বিজ্ঞপ্তি",
    chatbot: "চ্যাট সহায়ক",
    emergency: "জরুরি সহায়তা",
    familyMembers: "পরিবারের সদস্য",
    symptomChecker: "লক্ষণ পরীক্ষক",
    enterSymptoms: "আপনার লক্ষণ লিখুন...",
    send: "পাঠান",
    viewAll: "সব দেখুন",
    dueDate: "নির্ধারিত তারিখ",
    status: "অবস্থা",
    pending: "মুলতুবি",
    completed: "সম্পন্ন",
    severity: "তীব্রতা",
    high: "উচ্চ",
    medium: "মধ্যম",
    low: "কম",
    address: "ঠিকানা",
    contact: "যোগাযোগ",
    availability: "প্রাপ্যতা",
    available: "উপলব্ধ",
    busy: "ব্যস্ত",
    getDirections: "দিকনির্দেশ পান",
    typeMessage: "আপনার বার্তা টাইপ করুন...",
    startChat: "আশার সাথে চ্যাট শুরু করুন...",
    voiceInput: "ভয়েস ইনপুট",
    alreadyHaveAccount: "ইতিমধ্যে একটি অ্যাকাউন্ট আছে?",
    dontHaveAccount: "অ্যাকাউন্ট নেই?",
  },
  ml: {
    appName: "ആശാ ആരോഗ്യ സഹായി",
    login: "ലോഗിൻ ചെയ്യുക",
    signup: "സൈൻ അപ്പ് ചെയ്യുക",
    email: "ഇമെയിൽ",
    password: "പാസ്‌വേഡ്",
    confirmPassword: "പാസ്‌വേഡ് സ്ഥിരീകരിക്കുക",
    fullName: "പൂർണ്ണ നാമം",
    phone: "ഫോൺ നമ്പർ",
    age: "പ്രായം",
    gender: "ലിംഗഭേദം",
    male: "പുരുഷൻ",
    female: "സ്ത്രീ",
    other: "മറ്റുള്ളവ",
    location: "സ്ഥലം",
    dashboard: "ഡാഷ്‌ബോർഡ്",
    logout: "ലോഗ് ഔട്ട്",
    healthTips: "ആരോഗ്യ നുറുങ്ങുകൾ",
    vaccination: "വാക്സിനേഷൻ ഷെഡ്യൂൾ",
    outbreakAlerts: "പൊട്ടിപ്പുറപ്പെടൽ മുന്നറിയിപ്പുകൾ",
    hospitals: "ആശുപത്രികൾ കണ്ടെത്തുക",
    notifications: "അറിയിപ്പുകൾ",
    chatbot: "ചാറ്റ് സഹായി",
    emergency: "അടിയന്തര സഹായം",
    familyMembers: "കുടുംബാംഗങ്ങൾ",
    symptomChecker: "ലക്ഷണ പരിശോധന",
    enterSymptoms: "നിങ്ങളുടെ ലക്ഷണങ്ങൾ നൽകുക...",
    send: "അയയ്ക്കുക",
    viewAll: "എല്ലാം കാണുക",
    dueDate: "അവസാന തീയതി",
    status: "നില",
    pending: "തീർപ്പാക്കാത്തത്",
    completed: "പൂർത്തിയായി",
    severity: "തീവ്രത",
    high: "ഉയർന്ന",
    medium: "ഇടത്തരം",
    low: "താഴ്ന്ന",
    address: "വിലാസം",
    contact: "ബന്ധപ്പെടുക",
    availability: "ലഭ്യത",
    available: "ലഭ്യമാണ്",
    busy: "തിരക്കിലാണ്",
    getDirections: "ദിശകൾ നേടുക",
    typeMessage: "നിങ്ങളുടെ സന്ദേശം ടൈപ്പ് ചെയ്യുക...",
    startChat: "ആശയുമായി ചാറ്റ് ആരംഭിക്കുക...",
    voiceInput: "വോയ്‌സ് ഇൻപുട്ട്",
    alreadyHaveAccount: "ഇതിനകം ഒരു അക്കൗണ്ട് ഉണ്ടോ?",
    dontHaveAccount: "അക്കൗണ്ട് ഇല്ലേ?",
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('en');

  useEffect(() => {
    const savedLanguage = localStorage.getItem('language') as Language;
    if (savedLanguage && translations[savedLanguage]) {
      setLanguage(savedLanguage);
    }
  }, []);

  const handleSetLanguage = (lang: Language) => {
    setLanguage(lang);
    localStorage.setItem('language', lang);
  };

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage: handleSetLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
