// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tlzundrhshvgvmpfdnrs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRsenVuZHJoc2h2Z3ZtcGZkbnJzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTk0ODc2NjgsImV4cCI6MjA3NTA2MzY2OH0.Ia6vxLmZGoAEJgiqzw3XniBSzyjLH7_bGenYNEoBiWw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});